apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - $(TOKEN)
        image: cloudflare/cloudflared:2025.5.0
        name: cloudflared
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared
              key: token
