apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared 
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: vpn-vault
    kind: SecretStore
  target:
    name: cloudflared 
  data:
  - secretKey: token
    remoteRef:
      key: secret/cloudflare/tunnel/vpn
      property: token
